Task 2: Beta version of Rouglike
sloboegen98/RoguPacman pull request #2
Opened 2021-04-19 00:05 UTC by sloboegen98

2021-04-23 16:13 UTC, aleksZubakov requested changes
А как это собирать? Не могли бы Вы все-таки gradle использовать?

2021-04-26 01:26 UTC, sloboegen98 commented
> А как это собирать? Не могли бы Вы все-таки gradle использовать?

Заиспользовали `gradle`, в README написал как собирать из консоли. Если использовать idea, то, кажется, что она сама должна все подтянуть.

2021-04-27 23:40 UTC, aleksZubakov requested changes
В целом, ок. Не хватает комментариев и тестов (хоть каких-то), пока 8 баллов

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/app/ServerMain.java
> +        System.out.println("The server is running...");
Мелочь, но это все-таки луше внутри `try` делать, когда мы смогли сокет создать, т.к. могли и не создать и наврать в логах

2021-04-27 23:40 UTC, aleksZubakov commented on src/client/src/SimpleClient.java
> +                socket = new Socket(serverAddress, 8080);
`Socket` не просто так `AutoClosable` сделан, а для того, чтобы его удобно можно было закрывать. Очевидно, что это не просто так. Подумайте и напишите здесь почему его нужно закрывать, а после все-таки сделайте так, чтобы сокеты всегда закрывались

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/app/GameEngine.java
> +    private final Set<GameRoom> gameRooms = new HashSet<>();
Идея подсказывает, что в это множество только добавляются значения, но никогда не извлекаются.

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/app/GameEngine.java
> +    public enum GameMode {
Такой штуке лучше дать имя `Mode`, тогда внешние вызовы будут вида: `GameEngine.Mode.SINGLEPLAYER`, что также понятно, но лаконичнее

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/app/GameEngine.java
> +        synchronized (waitingAbstractUsers) {
Вы пока это не проходили, но вообще кажется, что тут могут проблемы быть, т.к. между синхронизациями что-то может произойти в другом треде. Но ок, исправлять не требуется сейчас

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/app/GameEngine.java
> +                createMultiPlayerRoom(abstractUser);
Маленький лайфхак: лучше используйте фигурные скобки, к их присутствию на каждом шагу в java все привыкли, зато никогда не забудете `break` написать:
```java
        switch (mode) {
            case MULTIPLAYER: {
                createMultiPlayerRoom(abstractUser);
            }
            case SINGLEPLAYER: {
                createSinglePlayerRoom(abstractUser);
            }
        }
```

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/app/GameEngine.java
> +                List<AbstractUser> abstractUserList = waitingAbstractUsers.parallelStream().limit(
А зачем тут `parallelStream`?

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/rooms/GameRoom.java
> +    public boolean goTo(int positionX, int positionY, @NotNull Character character) {
Тут идея подсказывает, что возвращаемое значение никогда не используется

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/user/AbstractUser.java
> +                while (input.hasNext()) {
В какой момент `hasNext` вернет `false`?

2021-04-27 23:40 UTC, aleksZubakov commented on src/server/src/main/user/AbstractUser.java
> +                        return;
Точно хорошая идея выкидывать пользователя, если пришла неверная команда? Или, мб, что-то более щадящее имеет смысл делать?

2021-05-03 00:40 UTC, sloboegen98 commented
Мобы добавились в этом же PR, так просто было сильно удобнее. Прошлые замечания немного поправили, но еще в процессе правок

2021-05-14 19:58 UTC, aleksZubakov commented
Засчитываю исправления

2021-05-14 19:58 UTC, closed without merging